"""v0.12

Revision ID: f9d122c1c0ce
Revises: 614e139bad12
Create Date: 2021-03-18 19:49:07.946530

"""

# revision identifiers, used by Alembic.
revision = 'f9d122c1c0ce'
down_revision = '614e139bad12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
